### ISSUE TITLE
rm-empty folders  with path not ends with '/' removes the entire path 

### ISSUE THREAD

**Issue by dantran** [jfrog/jfrog-cli-plugins-reg#149]
jf rm-empty folders dps-maven-staging/com
    12:40:30 [🔵Info] Searching for all items under dps-maven-staging/com
    12:40:30 [🔵Info] Searching artifacts...
    12:40:31 [🔵Info] Searching for items in Artifactory...
    12:40:32 [🔵Info] Found 1 artifact.
    12:40:32 [🔵Info] Found 1 empty folder.
      dps-maven-staging/com/
    Are you sure you want to delete the above paths? (y/n) [n]? n

if I hit yes, it will move my 'com' folder including of of its non empty folders  to trash

This is a severe bug

versions:

    jf --version
    jf version 2.63.0

    jf rm-empty --version
    rm-empty version v1.0.4

**Comment by eyalbe4** [comment]
@dantran,
It is best to post issues on the code repository that hosts the actual plugin and close this issue. 
This repository  merely serves as the registry for the plugin. Also, creating a pull request with the fix is the recommend approach.

**Comment by dantran** [comment]
see https://github.com/jfrog/jfrog-cli-plugins/issues/102
